services:
  mariadb:
    image: mariadb:latest@sha256:2d50fe0f77dac919396091e527e5e148a9de690e58f32875f113bef6506a17f5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pollux
      MYSQL_USER: pollux
      MYSQL_PASSWORD: pollux
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
