services:
  mariadb:
    image: mariadb:latest@sha256:0b5f0d3cace822485ddd03465334909a11ccda5742b29425ae10eb19dae85348
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pollux
      MYSQL_USER: pollux
      MYSQL_PASSWORD: pollux
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
