services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pollux
      MYSQL_USER: pollux
      MYSQL_PASSWORD: pollux
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
