services:
  mariadb:
    image: mariadb:latest@sha256:a9547599cd87d7242435aea6fda22a9d83e2c06d16c658ef70d2868b3d3f6a80
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pollux
      MYSQL_USER: pollux
      MYSQL_PASSWORD: pollux
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
