services:
  mariadb:
    image: mariadb:latest@sha256:bfb1298c06cd15f446f1c59600b3a856dae861705d1a2bd2a00edbd6c74ba748
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pollux
      MYSQL_USER: pollux
      MYSQL_PASSWORD: pollux
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
